-- =====================================================================
--  BASE DE DATOS PARA UNA INMOBILIARIA NUEVA
--  Supabase > SQL Editor > New query > pegar todo > Run
--  (se corre una sola vez, en el proyecto NUEVO de la inmobiliaria)
-- =====================================================================

-- ---------- PROPIEDADES ----------
create table if not exists public.propiedades (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  operacion           text,             -- venta / alquiler
  tipo                text,
  subtipo             text,
  calle               text,
  provincia           text,
  ciudad              text,
  barrio              text,
  codigo_postal       text,
  ubicacion_exacta    text default 'si',
  direccion           text,
  sup_total           numeric,
  sup_cubierta        numeric,
  antiguedad_tipo     text,
  antiguedad_anios    numeric,
  ambientes           numeric,
  dormitorios         numeric,
  banos               numeric,
  toilettes           numeric,
  cocheras            numeric,
  caracteristicas     jsonb default '[]'::jsonb,
  balcon              text,
  patio               text,
  pileta              text,
  quincho             text,
  luminosidad         text,
  orientacion         text,
  cantidad_plantas    numeric,
  cochera             text,
  frente_terreno      numeric,
  largo_terreno       numeric,
  titulo              text not null,
  descripcion         text,
  codigo_interno      text,
  precio              numeric,
  moneda              text default 'USD',
  apto_credito        text default 'no',
  expensas            text,
  sin_expensas        text default 'no',
  escritura           text,
  estado              text default 'activa',   -- activa / reservada / inactiva
  fotos               text default '[]',       -- lista de links (JSON)
  destacada           text default 'no',
  mostrar_inicio      text,
  zonaprop_id         bigint,
  zonaprop_codigo     text,
  zonaprop_plan       text,
  zonaprop_vinculado_en timestamptz
);

-- ---------- CONSULTAS (formularios de la web) ----------
create table if not exists public.consultas (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  nombre      text,
  telefono    text,
  email       text,
  interes     text,
  mensaje     text,
  origen      text
);

-- ---------- MÚSICA ----------
create table if not exists public.musica (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  titulo      text,
  compositor  text,
  interprete  text,
  url         text,
  archivo     text,
  activa      boolean default true,
  orden       integer default 0
);

create table if not exists public.musica_config (
  id                integer primary key,
  minutos_por_obra  numeric default 0,
  modo              text default 'orden'
);
insert into public.musica_config (id) values (1) on conflict (id) do nothing;

-- ---------- PERMISOS (RLS) ----------
-- Visitantes: ven propiedades y música, y pueden ENVIAR consultas (no leerlas).
-- Usuario logueado en el admin: puede todo.
alter table public.propiedades   enable row level security;
alter table public.consultas     enable row level security;
alter table public.musica        enable row level security;
alter table public.musica_config enable row level security;

create policy "ver propiedades"      on public.propiedades   for select using (true);
create policy "admin propiedades"    on public.propiedades   for all to authenticated using (true) with check (true);

create policy "enviar consulta"      on public.consultas     for insert to anon, authenticated with check (true);
create policy "admin consultas"      on public.consultas     for all to authenticated using (true) with check (true);

create policy "ver musica"           on public.musica        for select using (true);
create policy "admin musica"         on public.musica        for all to authenticated using (true) with check (true);

create policy "ver musica config"    on public.musica_config for select using (true);
create policy "admin musica config"  on public.musica_config for all to authenticated using (true) with check (true);

-- ---------- ARCHIVOS (fotos y música) ----------
insert into storage.buckets (id, name, public) values ('propiedades', 'propiedades', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('musica', 'musica', true) on conflict (id) do nothing;

create policy "ver archivos"     on storage.objects for select using (bucket_id in ('propiedades', 'musica'));
create policy "subir archivos"   on storage.objects for insert to authenticated with check (bucket_id in ('propiedades', 'musica'));
create policy "editar archivos"  on storage.objects for update to authenticated using (bucket_id in ('propiedades', 'musica'));
create policy "borrar archivos"  on storage.objects for delete to authenticated using (bucket_id in ('propiedades', 'musica'));

-- IMPORTANTE: en Authentication > Sign In / Providers, desactivar
-- "Allow new users to sign up" y crear a mano el usuario del admin
-- (Authentication > Users > Add user). Si no, cualquiera podría
-- registrarse y quedar con permisos de admin.
